#! /bin/sh

#############
# Variables #
#############

PANEL_FIFO="$HOME/.config/panel/fifo"
PANEL_HEIGHT="16"

COLOR_FOREGROUND='#FFA3A6AB'
COLOR_BACKGROUND='#FF34322E'
COLOR_ACTIVE_MONITOR_FG='#FF34322E'
COLOR_ACTIVE_MONITOR_BG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_FG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_BG='#FF34322E'
COLOR_FOCUSED_OCCUPIED_FG='#FFF6F9FF'
COLOR_FOCUSED_OCCUPIED_BG='#FF5C5955'
COLOR_FOCUSED_FREE_FG='#FFF6F9FF'
COLOR_FOCUSED_FREE_BG='#FF6D561C'
COLOR_FOCUSED_URGENT_FG='#FF34322E'
COLOR_FOCUSED_URGENT_BG='#FFF9A299'
COLOR_OCCUPIED_FG='#FFA3A6AB'
COLOR_OCCUPIED_BG='#FF34322E'
COLOR_FREE_FG='#FF6F7277'
COLOR_FREE_BG='#FF34322E'
COLOR_URGENT_FG='#FFF9A299'
COLOR_URGENT_BG='#FF34322E'
COLOR_LAYOUT_FG='#FFA3A6AB'
COLOR_LAYOUT_BG='#FF34322E'
COLOR_TITLE_FG='#FFA3A6AB'
COLOR_TITLE_BG='#FF34322E'
COLOR_STATUS_FG='#FFA3A6AB'
COLOR_STATUS_BG='#FF34322E'

##########################
# Preparations for panel #
##########################

# Kill any open panel processes.
while [ $(pgrep -cx panel) -gt 1 ] ; do
	pkill -ox -9 panel
done

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

####################
# Helper functions #
####################

function clock {
    while true; do
        TZ=Europe/Helsinki date +"S%d/%m %H:%M"
        sleep 1
    done
}

BAT="/sys/class/power_supply/BAT1"

function battery {
    while true; do
        STATUS=`cat $BAT/status`
        CAPACITY=`cat $BAT/capacity`
        AC_ONLINE=`cat /sys/class/power_supply/AC/online`

        if [ $STATUS == "Charging" ]; then
            STATUS="\uf0e7 "
        elif [ $AC_ONLINE == "1" ]; then
            STATUS="\uf1e6 "
        else
            STATUS=""
        fi

        if [ $CAPACITY -gt "90" ]; then
            CAPACITY="\uf240"
        elif [ $CAPACITY -gt "75" ]; then
            CAPACITY="\uf241"
        elif [ $CAPACITY -gt "50" ]; then
            CAPACITY="\uf242"
        elif [ $CAPACITY -gt "25" ]; then
            CAPACITY="\uf243"
        else
            CAPACITY="\uf244"
        fi

        echo -e "B$STATUS$CAPACITY"
        sleep 1
    done
}

function connman_networkstatus () {
    while true; do
        ethernet=`connmanctl technologies | grep -A 5 technology/ethernet | grep Connected | awk '{print $3}'`
        wifi=`connmanctl technologies | grep -A 5 technology/wifi | grep Connected | awk '{print $3}'`
        bluetooth=`connmanctl technologies | grep -A 5 technology/bluetooth | grep Connected | awk '{print $3}'`

        if [ $ethernet == "True" ]; then
            ethernet="\uf26b"
        else
            ethernet=""
        fi

        if [ $wifi == "True" ]; then
            wifi="\uf1eb"
        else
            wifi=""
        fi

        if [ $bluetooth == "True" ]; then
            bluetooth="\uf293"
        else
            bluetooth=""
        fi

        echo -e "C$ethernet$wifi$bluetooth"
        sleep 1
    done
}

################
# Pipe to fifo #
################

clock > "$PANEL_FIFO" &
bspc control --subscribe > "$PANEL_FIFO" &

if [[ $(hostname) == 'serendipity' ]]; then
    battery > "$PANEL_FIFO" &
    connman_networkstatus > "$PANEL_FIFO" &
fi

#################
# Lemonbar pipe #
#################

function panel_bar {
    while read line < $PANEL_FIFO; do
        case $line in
            S*)
                date="${line#?}"
                ;;
            B*)
                percent="${line#?}"
                ;;
            C*)
                connection="${line#?}"
                ;;
        esac

        fmt="%{r}${connection}  ${percent}  ${date}"

        printf "%s\n" "$fmt"
    done
}

panel_bar | lemonbar -g x$PANEL_HEIGHT -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -f "Droid Sans-10" -f "FontAwesome-12" &

wait
