#! /bin/sh

# Install programs
sudo pacman -Syuu git

# Git defaults
git config --global core.editor "vim"
git config --global remote.origin.prune true
git config --global pull.ff only
git config --global rebase.autoSquash true
