#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus      true

if [[ $(hostname) == 'destiny' ]]; then
    bspc monitor DFP1 -d I II III
    bspc monitor DFP14 -d IV V VI
    bspc monitor DFP9 -d VII VIII IX
    bspc monitor DFP13 -d X

    bspc monitor DFP1 -s DFP14
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Emacs state=tiled

panel &
