#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DFP1 -d I II III
bspc monitor DFP14 -d IV V VI
bspc monitor DFP9 -d VII VIII IX
bspc monitor DFP13 -d X

bspc monitor DFP14 -s DFP9
bspc monitor DFP9 -s DFP13

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
